name: Pull YT
on:
  schedule:
    - cron: '0 0/2 * * *'

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "newf@gmail.com"
        git config --global user.name "newf276"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get Al Jazeera
      run: |
        touch ./aljazeera.m3u8
        sudo cat >./aljazeera.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/live/gCNeDWCI0vo?si=oj2bE7kvkfHY1sEt)
        EOL
    - name: Get CBS News.m3u8
      run: |
        touch ./cbsnews.m3u8
        sudo cat >./cbsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/UC8p1vwvWtl6T73JiExfWs1g/live)
        EOL

    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push -f
