name: Filter By Events
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  filter-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download full channel list
        run: curl -L -o original.m3u "https://daddylive-4o1o.onrender.com/playlist/events"

      - name: Convert file to UTF-8
        run: iconv -f ISO-8859-1 -t UTF-8 original.m3u -o original_utf8.m3u

      - name: Extract Selected Countries
        run: |
          echo '#EXTM3U url-tvg="https://github.com/pigzillaaaaa/daddylive/raw/refs/heads/main/epgs/daddylive-events-epg.xml"' > hockey_channels.m3u
          grep -A 1 -i 'group-title="ICE HOCKEY"' original_utf8.m3u | grep -v -- "^--$" >> hockey_channels.m3u

          echo '#EXTM3U url-tvg="https://github.com/pigzillaaaaa/daddylive/raw/refs/heads/main/epgs/daddylive-events-epg.xml"' > soccer_channels.m3u
          grep -A 1 -i 'group-title="SOCCER"' original_utf8.m3u | grep -v -- "^--$" >> soccer_channels.m3u

          echo '#EXTM3U url-tvg="https://github.com/pigzillaaaaa/daddylive/raw/refs/heads/main/epgs/daddylive-events-epg.xml"' > mlb_channels.m3u
          grep -A 1 -i 'group-title="BASEBALL"' original_utf8.m3u | grep -v -- "^--$" >> mlb_channels.m3u

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add hockey_channels.m3u
          git add soccer_channels.m3u
          git add mlb_channels.m3u
          git rm original.m3u
          git rm original_utf8.m3u
          git commit -m "Fetched and Updated Events Lists"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}