name: Filter By Countries
on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  filter-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download full channel list
        run: curl -L -o original.m3u "https://newf276-gtvhome.hf.space/playlist/channels"

      - name: Convert file to UTF-8
        run: iconv -f ISO-8859-1 -t UTF-8 original.m3u -o original_utf8.m3u

      - name: Extract Selected Countries
        run: |
          echo '#EXTM3U url-tvg="https://raw.githubusercontent.com/pigzillaaaaa/daddylive/refs/heads/main/epgs/daddylive-channels-epg.xml"' > usa_channels.m3u
          grep -A 1 -i 'group-title="United States"' original_utf8.m3u | grep -v -- "^--$" >> usa_channels.m3u

          echo '#EXTM3U url-tvg="https://raw.githubusercontent.com/pigzillaaaaa/daddylive/refs/heads/main/epgs/daddylive-channels-epg.xml"' > uk_channels.m3u
          grep -A 1 -i 'group-title="United Kingdom"' original_utf8.m3u | grep -v -- "^--$" >> uk_channels.m3u

          echo '#EXTM3U url-tvg="https://raw.githubusercontent.com/pigzillaaaaa/daddylive/refs/heads/main/epgs/daddylive-channels-epg.xml"' > canada_channels.m3u
          grep -A 1 -i 'group-title="Canada"' original_utf8.m3u | grep -v -- "^--$" >> canada_channels.m3u

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add *.m3u
          git commit -m "Fetched and Updated Group Lists"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}