name: Make Free Programme
on:
  schedule:
    - cron: '00 00-12/6 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          git pull
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: generate
        run: |
          cd programme/scripts
          pwd       
          echo "Installing dependencies..."
          python3 -m pip install lxml
          echo "Generating Programme..."
          python3 index.py guide.xml free/free.txt "action@github.com" "GitHub Action"
          sleep 3
          python3 index.py free.xml free/free.txt "action@github.com" "GitHub Action"
          "GitHub Action"
          gzip -9 -f free.xml
          cd ..
      - name: commit
        run: |
          git add -A
          git commit -m "Make Free Programme"
          git push


