name: Parser

on:
  schedule:
    # Runs once a day at midnight
    - cron: '0 */2 * * *'
  
  # Add a manual trigger
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (no history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests
      - name: Run EPG grabber script
        run: |
          python parser.py

      - name: config
        run: |
          git pull
          git config --global user.email "newf@gmail.com"
          git config --global user.name "newf276"
          
      - name: commit
        run: |
          git add -A
          git commit -m "updated"
          git push