name: Parse i-mjh xmls

on:
  schedule:
    # Runs twice a day
    - cron: '0 */1 * * *'
  
  # Add a manual trigger
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install requests

      - name: Run Parser
        run: |
          python parser.py

      - name: Force commit and push the changes (no history)
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add parser.xml parser.xml.gz
          git commit -m "Update Parser XML"
          git push --force # Force push to overwrite the previous commit
