name: ripper
on:
  schedule:    
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Downloading ripper file...
      run: |
        cd /home/runner/work/newf276/junk/pull/
        chmod +x download.sh
        bash ./download.sh
