name: ripper
on:
  schedule:    
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Downloading Files...
      run: |
        echo Downloading Files...
        exec 3>&1 &>/dev/null
        cd /home/runner/work/newf276/junk/pull/
        openssl aes-256-cbc -in keys.txt.enc -out keys.txt -d -pass pass:${{ secrets.KEY }}
        base64 --decode keys.txt > keys.txt.1
        rm keys.txt ; mv keys.txt.1 keys.txt
        cat keys.txt download.sh > temp.txt ; mv temp.txt file2.txt ; rm download.sh ; mv file2.txt download.sh ; chmod +x download.sh
        /home/runner/work/newf276/junk/pull/download.sh

